# ansible-playbook aws_avicontroller.yml --ask-vault

- name: Deploy Avi Controller instance 
  hosts: localhost
  gather_facts: False
  vars_files:
    - aws_keys.yml
    - vars.yml
  # vars_prompt:
  #   - name: "AccessKey"
  #     prompt: "Enter AWS Access Key"
  #   - name: "SecretKey"
  #     prompt: "Enter AWS Secret Key"
  # vars:
  tasks:
    - name: Create instance usi Avi Controller AMI
      ec2:
        aws_access_key: "{{ AccessKey }}"
        aws_secret_key: "{{ SecretKey }}"
        instance_type: "{{ aws_instance_type|default('m4.2xlarge') }}" 
        image: "{{ controller_ami }}" 
        group: "{{ aws_security_group }}"
        key_name: "{{ aws_keypair }}"
        region: "{{ aws_region }}"
        zone: "{{ aws_zone }}"
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 64
            delete_on_termination: true
        ebs_optimized: true
        # user_data: "{{ lookup('file', 'setup.json') }}"  # mind the trailing space in setup.json
        user_data: ""
        wait: yes
        count: 1
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        instance_tags: "{{ aws_tags }}"
        
      register: ec2

    - name: Display public IP
      debug: msg="Here is the public ip {{ item.public_ip }}"
      with_items: "{{ ec2.instances }}"